name: Documentation

on:
  push:
    paths:
      - "Include/**"

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: Documentation/
          
      - name: Commit and push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add .
          git commit -m "Update Build from ${GITHUB_SHA::7}"
          git push
