name: Guidelines Table of Contents

on:
  push:
    paths:
      - "GUIDELINES.md"
      - ".github/workflows/toc.js"
      - ".github/workflows/guide-toc.yml"

jobs:
  toc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
    
      - name: Generate TOC
        run: node .github/workflows/toc.js GUIDELINES.md

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update guidelines from \[${GITHUB_SHA::8}]
